[[headers]]
for = "/*"
[headers.values]
Referrer-Policy = "no-referrer"

[[redirects]]
from = "/status"
to = "/status.html"
status = 200
force = true

[[redirects]]
from = "/"
to = "https://fayln.com"
status = 307
force = true

[[redirects]]
from = "/github/*"
to = "https://github.com/faridhnzz/:splat"
status = 307
force = true

[[redirects]]
from = "/instagram"
to = "https://www.instagram.com/faridhnzz/"
status = 307
force = true

[[redirects]]
from = "/twitter"
to = "https://twitter.com/faridhnzz"
status = 307
force = true

[[redirects]]
from = "/polywork"
to = "https://www.polywork.com/faridnizam"
status = 307
force = true

[[redirects]]
from = "/linkedin"
to = "https://www.linkedin.com/in/faridhnzz/"
status = 307
force = true
